version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - 'dependencies'
    rebase-strategy: disabled

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
      time: "04:00"
    open-pull-requests-limit: 20
    labels:
      - dependencies
    rebase-strategy: disabled
